import datetime

try:
    from fpdf import FPDF
    _FPDF = True
except ImportError:
    _FPDF = False


def generate_report(aoi_coords, mca_weights, sar_params, results):
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    return f"""
==================================================
HYDRO-CLIMATIC RISK ATLAS — TECHNICAL REPORT
Generated : {now}
==================================================
INVESTIGATOR : Ankit Kumar
INSTITUTION  : IIT Kharagpur
--------------------------------------------------
1. STUDY AREA (AOI)    : {aoi_coords}
2. MCA WEIGHTS         : LULC={mca_weights['lulc']}%  Slope={mca_weights['slope']}%  Rain={mca_weights['rain']}%
3. SAR POLARISATION    : {sar_params.get('polarization','VH')}
4. SAR WINDOWS (Pre)   : {sar_params['pre_start']} → {sar_params['pre_end']}
5. SAR WINDOWS (Post)  : {sar_params['f_start']} → {sar_params['f_end']}
6. THRESHOLD           : {sar_params['threshold']} dB
7. SPECKLE FILTER      : {'Lee (focal_mean 3×3)' if sar_params.get('speckle') else 'None'}
8. INUNDATED AREA      : {results['area_ha']} Ha
9. POPULATION EXPOSED  : {results.get('pop_exposed', 'N/A')}
==================================================
"""


def generate_pdf_bytes(aoi_coords, mca_weights, sar_params, results, rp_data=None):
    if not _FPDF:
        return None
    try:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()
        pdf.set_margins(20, 20, 20)

        pdf.set_font('Helvetica', 'B', 18)
        pdf.cell(0, 14, 'HYDRO-CLIMATIC RISK ATLAS', ln=True)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f'IIT Kharagpur  |  {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', ln=True)
        pdf.ln(4)
        pdf.set_draw_color(0, 200, 200)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(5)

        def section(title):
            pdf.set_text_color(0, 0, 0)
            pdf.set_font('Helvetica', 'B', 11)
            pdf.cell(0, 8, title, ln=True)
            pdf.set_font('Helvetica', '', 10)

        section('1. STUDY AREA')
        pdf.multi_cell(0, 6, f'AOI Coordinates: {aoi_coords}')
        pdf.ln(3)

        section('2. MCA ANALYSIS WEIGHTS')
        pdf.cell(57, 6, f'LULC: {mca_weights["lulc"]}%')
        pdf.cell(57, 6, f'Slope: {mca_weights["slope"]}%')
        pdf.cell(57, 6, f'Rainfall: {mca_weights["rain"]}%', ln=True)
        pdf.ln(3)

        section('3. SAR INUNDATION ANALYSIS')
        rows = [
            ('Polarisation', sar_params.get('polarization','VH')),
            ('Pre-flood window', f'{sar_params["pre_start"]} → {sar_params["pre_end"]}'),
            ('Post-flood window', f'{sar_params["f_start"]} → {sar_params["f_end"]}'),
            ('Change threshold', f'{sar_params["threshold"]} dB'),
            ('Speckle filter', 'Lee focal_mean 3x3' if sar_params.get('speckle') else 'None'),
        ]
        for k, v in rows:
            pdf.cell(65, 6, k + ':')
            pdf.cell(0, 6, str(v), ln=True)
        pdf.ln(3)

        section('4. RESULTS')
        pdf.cell(65, 6, 'Inundated Area:')
        pdf.cell(0, 6, f'{results["area_ha"]} Ha', ln=True)
        pdf.cell(65, 6, 'Population Exposed:')
        pdf.cell(0, 6, str(results.get('pop_exposed', 'N/A')), ln=True)
        pdf.ln(3)

        if rp_data and rp_data.get('return_periods'):
            section('5. FLOOD RETURN PERIODS  [Gumbel Distribution]')
            pdf.cell(65, 6, f'Analysis period: {rp_data.get("n_years",24)} years (2000-2023)', ln=True)
            pdf.cell(65, 6, f'Mean monsoon rain: {rp_data.get("mean",0)} mm')
            pdf.cell(0, 6, f'Std dev: {rp_data.get("std",0)} mm', ln=True)
            pdf.ln(2)
            for T, val in rp_data['return_periods'].items():
                pdf.cell(65, 6, f'  {T}-year return period:')
                pdf.cell(0, 6, f'{val:.0f} mm (monsoon total)', ln=True)
            pdf.ln(3)

        pdf.set_font('Helvetica', 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 6, 'Generated by HydroRisk Atlas | IIT Kharagpur | Powered by Google Earth Engine', ln=True)
        return bytes(pdf.output())
    except Exception:
        return None
